DCDUBE-637 Document helm chart upgrade
atlassian/data-center-helm-charts pull request #304
Opened 2021-09-20 05:34 UTC by nghazali

2021-09-21 01:56 UTC, tan-ro approved these changes

2021-09-24 00:16 UTC, errcode1202 requested changes

2021-09-24 00:16 UTC, errcode1202 commented on docs/docs/userguide/OPERATION.md
> +To learn about upgrading the products without upgrading the Helm charts see [Products upgrade](upgrades/PRODUCTS_UPGRADE.md).
```suggestion
* To learn about upgrading the Helm charts see [Helm chart upgrade](upgrades/HELM_CHART_UPGRADE.md).  
* To learn about upgrading the products without upgrading the Helm charts see [Products upgrade](upgrades/PRODUCTS_UPGRADE.md).
```

2021-09-24 00:16 UTC, errcode1202 commented on docs/docs/userguide/upgrades/HELM_CHART_UPGRADE.md
> +* the target version of the product you want to upgrade to
These bullet points dont render properly without a space after `Before upgrading the Helm chart, first consider: `
```suggestion
Before upgrading the Helm chart, first consider: 

* the version of the current Helm chart
* the version of the product running on your Kubernetes cluster
* the target version of the Helm chart you want to upgrade to
* the target version of the product you want to upgrade to
```

2021-09-24 00:44 UTC, errcode1202 approved these changes

2021-09-24 00:49 UTC, merged