Document update for PR#334
atlassian/data-center-helm-charts pull request #368
Opened 2022-01-11 04:18 UTC by jjeongatl

2022-01-11 06:25 UTC, nanux commented on docs/docs/examples/storage/additional storage/ADDTIONAL_STORAGE.md
> +confluence:
This should also show how to use the new volume with `additionalMounts` property.

2022-01-12 01:58 UTC, errcode1202 requested changes

2022-01-12 01:58 UTC, errcode1202 commented on docs/docs/examples/storage/additional storage/ADDTIONAL_STORAGE.md
> +```yaml
Typo - `volumn` should be `volume`

2022-01-12 02:08 UTC, errcode1202 commented
can the directory; `docs/docs/examples/storage/additional storage` be renamed to: `docs/docs/examples/storage/additional_storage`

2022-01-12 05:34 UTC, nghazali approved these changes

2022-01-12 06:21 UTC, yzha645 approved these changes

2022-01-12 22:15 UTC, merged