CLIP-1413: Fix synchrony ingress path
atlassian/data-center-helm-charts pull request #422
Opened 2022-06-30 23:26 UTC by nghazali

* synchrony path fix
* This PR is a contribution from community (https://github.com/atlassian/data-center-helm-charts/pull/420)
Merging to CLIP-1413-fix-synchrony-ingress-path branch to run e2e tests

## Pull request description

Allows synchrony to work with or without context path that is driven from the ingress.host used for the confluence application. The context path for synchrony would always be /synchrony and that context path would be reserved for synchrony. I think it removes some of the confusion in the values.yaml around the ingress hosts and context paths and also a lot of the cross-walking of the configuration. There doesn't appear to be much benefit to have the ingress host for synchrony to be configurable as it is only for collaborative editing. A user does not necessarily route to this url directly to use collaborative editing. It just happens in the background. In most cases if the network/web server path to ingress.host is open, then the network path to synchrony will also be open. Currently, the synchrony url does not work with a context path due to incorrect value being placed in the ingress for the synchrony context path.
_Provide description for the PR_

## Checklist
- [x] I have added unit tests
- [x] I have applied the change to all applicable products
- [x] I have added the change description to the `changelog.md` and `Chart.yaml` files
- [x] (Atlassian only) Internal Bamboo CI is passing

2022-07-05 05:25 UTC, nanux commented
The changes are looking good. Thanks @bordenit for the contribution and @nghazali for shepherding the change.

@nghazali could you please add the change description to the `changelog.md` and `Chart.yaml` files.

2022-07-05 05:26 UTC, nanux requested changes
@nghazali could you please add the change description to the `changelog.md` and `Chart.yaml` files.

2022-07-06 01:20 UTC, nghazali commented
Hi @nanux , the required changes are applied now.

2022-07-06 03:29 UTC, nanux approved these changes

2022-07-06 05:05 UTC, jjeongatl approved these changes

2022-07-06 05:42 UTC, merged