CLIP-1520: Make ATL_FORCE_CFG_UPDATE configurable in values.yaml
atlassian/data-center-helm-charts pull request #454
Opened 2022-09-29 03:03 UTC by bianchi2

## Pull request description

This PR introduces a new env to values.yaml to add `ATL_FORCE_CFG_UPDATE` to container env if `<product-name>.forceConfigUpdate` is set to true.

The following files are affected:
* Jira: `dbconfig.xml`
* Confluence: `confluence.cfg.xml`
* Bamboo: `bamboo.cfg.xml`

The default value is false, i.e. the above config files are not overwritten, i.e. nothing is changed in terms of previous defaults. This can be discussed though

## Checklist
- [ ] I have added unit tests
- [ ] I have applied the change to all applicable products
- [ ] I have added the change description to the `changelog.md` and `Chart.yaml` files
- [ ] (Atlassian only) I have run the E2E test (if applicable)
- [ ] (Atlassian only) Internal Bamboo CI is passing

2022-10-12 20:35 UTC, nanux requested changes

2022-10-17 21:26 UTC, bianchi2 commented on docs/docs/userguide/CONFIGURATION.md
> +or set it in values.yaml:
Fixed

2022-10-17 21:26 UTC, bianchi2 commented on src/main/charts/bamboo/values.yaml
> +  # By default, bamboo.cfg.xml is generated only once. Set configOverwrite to true
Fixed

2022-10-17 21:26 UTC, bianchi2 commented on src/main/charts/bamboo/values.yaml
> +  # to change this behavior. ATL_FORCE_CFG_UPDATE=true will be added to container env.
Removed

2022-10-17 21:27 UTC, bianchi2 commented on src/main/charts/jira/values.yaml
> +  # By default, dbconfig.xml is generated only once. Set configOverwrite to true
Fixed

2022-10-17 21:27 UTC, bianchi2 commented on src/test/java/test/ForceCfgUpdateEnvVarTest.java
> +class ForceCfgUpdateEnvVarTest {
Renamed

2022-10-17 21:27 UTC, bianchi2 commented on src/test/java/test/ForceCfgUpdateEnvVarTest.java
> +    @EnumSource(value = Product.class, names = "jira")
I thought it's the same templating logic so one product is enough. Added the other two.

2022-10-18 00:19 UTC, tarka approved these changes
As discussed elsewhere, this isn't guaranteed to stick with Confluence, as it doesn't necessarily honour all values in a provided `confluence.cfg.xml`. However it will help in the case that a bad config needs to be reset, which is what I believe the original issue was here.

2022-10-18 22:21 UTC, nanux approved these changes

2022-10-18 23:07 UTC, merged