bamboo agent add additional volumes and mounts
atlassian/data-center-helm-charts pull request #537
Opened 2023-03-22 11:12 UTC by timmy59100

## Pull request description

Provides support for additional volume and volume mounts for bamboo-agent as described in issue https://github.com/atlassian/data-center-helm-charts/issues/530

## Checklist
- [ ] I have added unit tests
- [ ] I have applied the change to all applicable products
- [ ] The E2E test has passed (use `e2e` label)
- [ ] (Atlassian only) Internal Bamboo CI is passing

2023-03-22 19:43 UTC, bianchi2 requested changes

2023-03-22 19:43 UTC, bianchi2 commented on src/main/charts/bamboo-agent/templates/deployment-agent.yaml
> +        {{ include "bamboo-agent.volumes" . | nindent 8 }}
Can we rename it to `bamboo-agent.additionalVolumes`?

2023-03-23 03:54 UTC, bianchi2 commented
@timmy59100 can you also sign CLA please?

2023-03-28 12:25 UTC, timmy59100 commented
I put the wrong email in the CLA, i requested a change from the team but didn't hear anything.

2023-03-29 02:04 UTC, bianchi2 approved these changes

2023-04-14 21:12 UTC, bianchi2 commented
@timmy59100 we're planning a release soon and I'll be happy to include merge your PR so that changes make it to the new release. Were you able to sort out CLA issues?

2023-04-24 03:45 UTC, nanux approved these changes

2023-05-02 15:31 UTC, timmy59100 commented
@bianchi2 No, I didn't hear from the team. Should I make a new pull request with the correct email?

2023-05-02 22:45 UTC, bianchi2 commented
@timmy59100 yes, please. Also, please make sure you use the latest main branch in your fork. Thanks

2023-05-03 23:21 UTC, closed without merging