Documentation for Crowd
atlassian/data-center-helm-charts pull request #544
Opened 2023-03-24 00:21 UTC by jjeongatl

## Pull request description

Missing documentation for Crowd

## Checklist
- [ ] I have added unit tests
- [ ] I have applied the change to all applicable products
- [ ] The E2E test has passed (use `e2e` label)
- [ ] (Atlassian only) Internal Bamboo CI is passing

2023-03-24 00:31 UTC, errcode1202 requested changes
Looks good, added some suggestions. Any reason why Crowd clustering is enabled by default?

2023-03-24 00:31 UTC, errcode1202 commented on docs/docs/userguide/CONFIGURATION.md
> +        Clustering is enabled by default. To disable clustering, set crowd.clustering.enabled to false in ${CROWD_HOME}/shared/crowd.cfg.xml and rollout restart Crowd StatefulSet after the initial pr
```suggestion
        Clustering is enabled by default. To disable clustering, set `crowd.clustering.enabled` to `false` in `${CROWD_HOME}/shared/crowd.cfg.xml` and rollout restart Crowd StatefulSet after the initial product setup is complete.
```

2023-03-24 00:31 UTC, errcode1202 commented on docs/docs/userguide/CONFIGURATION.md
> +By default, the Helm charts will not configure the products for Data Center clustering except Crowd. In order to enable clustering, the `enabled` property for clustering must be set to `true`.
```suggestion
By default, the Helm charts will not configure the products for Data Center clustering. In order to enable clustering, the `enabled` property for clustering must be set to `true`.

!!!info "Clustering by default for Crowd"
    Clustering is enabled by default for Crowd. To disable clustering, set `crowd.clustering.enabled` to `false` in `${CROWD_HOME}/shared/crowd.cfg.xml` and rollout restart Crowd StatefulSet after the initial product setup is complete.
```

2023-03-24 00:44 UTC, jjeongatl commented on docs/docs/userguide/CONFIGURATION.md
> +By default, the Helm charts will not configure the products for Data Center clustering except Crowd. In order to enable clustering, the `enabled` property for clustering must be set to `true`.
This is explained in line 258

2023-03-24 03:32 UTC, bianchi2 approved these changes

2023-03-24 08:46 UTC, jjeongatl commented on docs/docs/userguide/CONFIGURATION.md
> +By default, the Helm charts will not configure the products for Data Center clustering except Crowd. In order to enable clustering, the `enabled` property for clustering must be set to `true`.
@errcode1202 addressed in new commit

2023-03-26 22:33 UTC, errcode1202 approved these changes

2023-03-26 22:34 UTC, merged